export enum PlatformRoute {
  Static = "#",
  Home = "/",
  CampaignDetails = "/mints/:campaignName",
  CampaignListing = "/mints",
  CharityDetails = "/charities/:charityName",
  CharityListing = "/charities",
  MarketplaceListing = "/marketplace",
  CreatorsListing = "/creators",
  CollectionDetails = "/collection/:collectionName",
  ItemDetails = "/fundraiser/:campaignName",
  FundraiserDetails = "/fundraisers",
  CreatorListing = "/creators",
  CreatorDetails = "/creators/:creatorName",
  ProfileDetails = "/profile/:role/:category",
}
