env:
  DEPLOY_TEST_ROLE_ARN: "arn:aws:iam::576424575048:role/DevOpsToolingAppDeployRole"
  DEPLOY_STAGE_ROLE_ARN: "arn:aws:iam::422397319486:role/DevOpsToolingAppDeployRole"
  DEPLOY_PROD_ROLE_ARN: "arn:aws:iam::247334077905:role/DevOpsToolingAppDeployRole"
  DEPLOY_TEST_ECR: "576424575048.dkr.ecr.ap-southeast-2.amazonaws.com"
  DEPLOY_STAGE_ECR: "422397319486.dkr.ecr.ap-southeast-2.amazonaws.com"
  DEPLOY_PROD_ECR: "247334077905.dkr.ecr.ap-southeast-2.amazonaws.com"

steps:
  - block: ":rocket: Build & Deploy Branch To Test"
    branches: "!master"
    
  - label: ":package: Test - Build Frontend Platform Project"
    command:
      - "echo 'Running Build & Push for container"
    env:
      AWS_ASSUME_ROLE_ARN: ${DEPLOY_TEST_ROLE_ARN}
    if: "build.branch != 'master'"
    plugins:
      - cultureamp/aws-assume-role
      - seek-oss/docker-ecr-publish#v2.4.0:
          dockerfile: apps/platform/Dockerfile
          build-context: ./apps/platform
          account_id: "576424575048"
          region: "ap-southeast-2"
          ecr-name: gtfrontend
          add-latest-tag: false
          args: 
            - COMMIT_SHA=$BUILDKITE_COMMIT
            - ENV=test
  - wait
  - label: ":rocket: Deploy Branch to Test"
    command:
      - "echo 'Deploying Branch to ECS...'"
      - "./ecs-deploy -c ecs-spot-test -n givetree-frontend -i ${DEPLOY_TEST_ECR}/gtfrontend:$$BUILDKITE_BUILD_NUMBER -t 600 --enable-rollback"
    if: "build.branch != 'master'"
    env:
      AWS_ASSUME_ROLE_ARN: ${DEPLOY_TEST_ROLE_ARN}
    plugins:
      - cultureamp/aws-assume-role
  
  - wait
  - block: ":rocket: Build & Deploy Master To Staging"
    branches: "master"
    
  - label: ":package: Staging - Build Frontend Platform Project"
    command:
      - "echo 'Running Build & Push for container"
    branches: "master"
    env:
      AWS_ASSUME_ROLE_ARN: ${DEPLOY_STAGE_ROLE_ARN}
    plugins:
      - cultureamp/aws-assume-role
      - seek-oss/docker-ecr-publish#v2.4.0:
          dockerfile: apps/platform/Dockerfile
          build-context: ./apps/platform
          account_id: "422397319486"
          region: "ap-southeast-2"
          ecr-name: gtfrontend
          add-latest-tag: false
          args: 
            - COMMIT_SHA=$BUILDKITE_COMMIT
            - ENV=stage
  - wait
  - label: ":rocket: Deploy Master to Staging"
    command:
      - "echo 'Deploying Branch to ECS...'"
      - "./ecs-deploy -c givetree -n givetree-frontend -i ${DEPLOY_STAGE_ECR}/gtfrontend:$$BUILDKITE_BUILD_NUMBER -t 600 --enable-rollback"
    branches: "master"
    env:
      AWS_ASSUME_ROLE_ARN: ${DEPLOY_STAGE_ROLE_ARN}
    plugins:
      - cultureamp/aws-assume-role
  - wait
  - block: ":rocket: Build & Deploy Master To Production"
    branches: "master"
    
  - label: ":package: Production - Build Frontend Platform Project"
    command:
      - "echo 'Running Build & Push for container"
    branches: "master"
    env:
      AWS_ASSUME_ROLE_ARN: ${DEPLOY_PROD_ROLE_ARN}
    plugins:
      - cultureamp/aws-assume-role
      - seek-oss/docker-ecr-publish#v2.4.0:
          dockerfile: apps/platform/Dockerfile
          build-context: ./apps/platform
          account_id: "247334077905"
          region: "ap-southeast-2"
          ecr-name: gtfrontend
          add-latest-tag: false
          args: 
            - COMMIT_SHA=$BUILDKITE_COMMIT
            - ENV=prod
  - wait
  - label: ":rocket: Deploy Master to Production"
    command:
      - "echo 'Deploying Branch to ECS...'"
      - "./ecs-deploy -c givetree -n givetree-frontend -i ${DEPLOY_PROD_ECR}/gtfrontend:$$BUILDKITE_BUILD_NUMBER -t 600 --enable-rollback"
    branches: "master"
    env:
      AWS_ASSUME_ROLE_ARN: ${DEPLOY_PROD_ROLE_ARN}
    plugins:
      - cultureamp/aws-assume-role
  