import { format } from "date-fns";
import { GetUserDetailsQuery } from "../../typed";
import { OnboardingFormValues } from "./onboarding-form/OnboardingForm.types";

export const getFormValues = (formData: GetUserDetailsQuery): OnboardingFormValues => ({
  aliasName: formData.users_by_pk?.aliasName || "",
  charityEntityType: formData.users_by_pk?.charityEntityType || "",
  charityAddress: formData.users_by_pk?.charityAddress || "",
  charityAbn: formData.users_by_pk?.charityAbn || "",
  charityAcceptDirectDonations:
    formData.users_by_pk?.charityAcceptDirectDonations || false,
  charityAllowProxyFundraiser: formData.users_by_pk?.charityAllowProxyFundraiser || false,
  charityApprovalBeforeGoLive: formData.users_by_pk?.charityApprovalBeforeGoLive || false,
  charityCreateFundraiser: formData.users_by_pk?.charityCreateFundraiser || false,
  contactNumber: formData.users_by_pk?.contactNumber || "",
  country: formData.users_by_pk?.country || "",
  cryptoActivityRating: formData.users_by_pk?.cryptoActivityRating || 1,
  cryptoConfidenceRating: formData.users_by_pk?.cryptoConfidenceRating || 1,
  cryptoExperienceRating: formData.users_by_pk?.cryptoExperienceRating || 1,
  cryptoOffRampStrategy: formData.users_by_pk?.cryptoOffRampStrategy || "",
  description: formData.users_by_pk?.description || "",
  discordUrl: formData.users_by_pk?.discordUrl || "",
  email: formData.users_by_pk?.email || "",
  ethWalletAddress: formData.users_by_pk?.ethWalletAddress || "",
  expectedReleaseDate:
    formData.users_by_pk?.expectedReleaseDate || format(new Date(), "yyyy-MM-dd"),
  firstName: formData.users_by_pk?.firstName || "",
  isArtworkReady: formData.users_by_pk?.isArtworkReady || false,
  lastName: formData.users_by_pk?.lastName || "",
  logoUrl: formData.users_by_pk?.logoUrl || "",
  maticWalletAddress: formData.users_by_pk?.logoUrl || "",
  primaryContactAddress: formData.users_by_pk?.primaryContactAddress || "",
  solWalletAddress: formData.users_by_pk?.solWalletAddress || "",
  twitterUrl: formData.users_by_pk?.twitterUrl || "",
  userType: formData.users_by_pk?.userType || "",
  websiteUrl: formData.users_by_pk?.websiteUrl || "",
});

export const getDefaultFormValues = (): OnboardingFormValues => ({
  aliasName: "",
  charityEntityType: "",
  charityAddress: "",
  charityAbn: "",
  charityAcceptDirectDonations: false,
  charityAllowProxyFundraiser: false,
  charityApprovalBeforeGoLive: false,
  charityCreateFundraiser: false,
  contactNumber: "",
  country: "",
  cryptoActivityRating: 1,
  cryptoConfidenceRating: 1,
  cryptoExperienceRating: 1,
  cryptoOffRampStrategy: "",
  description: "",
  discordUrl: "",
  email: "",
  ethWalletAddress: "",
  expectedReleaseDate: format(new Date(), "yyyy-MM-dd"),
  firstName: "",
  isArtworkReady: false,
  lastName: "",
  logoUrl: "",
  maticWalletAddress: "",
  primaryContactAddress: "",
  solWalletAddress: "",
  twitterUrl: "",
  userType: "",
  websiteUrl: "",
});
